agent:
  activation: elu
  active_ratio_emb_dim: 8
  bn_momentum: 1.0
  coupling_hidden_dim: 8
  dphase_emb_dim: 8
  dropout: 0.0
  gamma_emb_dim: 8
  mass_emb_dim: 8
  node_hidden_dim: 64
  node_type_emb_dim: 8
  perturbation_emb_dim: 8
  phase_emb_dim: 8
  power_emb_dim: 8
graph:
  mean_degree: 4.0
  num_nodes_distribution:
    avg: null
    delta: null
    max: 10.0
    min: 10.0
    name: uniform
    std: null
  shk_initial: 1
  shk_p: 0.2
  shk_q: 0.3
  shk_r: 0.3333
  shk_s: 0.1
  topology: shk
grid:
  consumer_max_units_distribution:
    avg: null
    delta: null
    max: 10.0
    min: 10.0
    name: uniform
    std: null
  consumer_num_ratio: 0.3
  sink_capacity_distribution:
    avg: null
    delta: 4.0
    max: null
    min: null
    name: uniform_wo_avg
    std: null
  sink_num_ratio: 0.1
  sink_spare: 1.0
  coupling_distribution:
    avg: null
    delta: null
    max: 10.0
    min: 10.0
    name: uniform
    std: null
  generator_capacity_distribution:
    avg: null
    delta: 4.0
    max: null
    min: null
    name: uniform_wo_avg
    std: null
  generator_num_ratio: 0.4
  generator_spare: 1.0
  initial_active_ratio: 0.5
  initial_max_rebalance: 1000
  initial_rebalance: directed
  renewable_capacity_distribution:
    avg: null
    delta: 4.0
    max: null
    min: null
    name: uniform_wo_avg
    std: null
  renewable_mass_distribution:
    avg: null
    delta: null
    max: 0.1
    min: 0.1
    name: uniform
    std: null
  renewable_num_ratio: 0.2
  source_ratio: 4.0
node:
  consumer_unit_gamma: 1.0
  consumer_unit_mass: 1.0
  consumer_unit_power: -1
  sink_unit_gamma: 1.0
  sink_unit_mass: 1.0
  sink_unit_power: -1
  generator_unit_gamma: 1.0
  generator_unit_mass: 1.0
  generator_unit_power: 1
  renewable_unit_gamma_mass_ratio: 1.0
  renewable_unit_power: 1
observation:
  active_ratio: true
  coupling: true
  dphase: true
  edge_list: true
  gamma: true
  mass: true
  node_type: true
  perturbation: true
  phase: true
  power: true
rl:
  equilibrium_time: 1
  fail_threshold: 0.01
  failed_scale: 1.0
  max_rebalance: 1000
  num_pertubation: 1
  num_steps_per_episode: 1000
  rebalance: directed
  reset_coupling: false
  reset_graph: false
  reset_node: true
  reset_node_type: false
  reward: weighted_area
  stable_threshold: 0.0001
  steady_time: 20
swing:
  _dt: 0.001
  _dtype: 32
  name: rk4
